name: Get AWS CDK Dependencies
description: Retrieves the Node.js packages from an AWS CDK release by tag
branding:
  icon: package
  color: purple
inputs:
  token:
    description: "Your GitHub token"
    required: true
  release:
    description: "The release of the AWS CDK release you woulld like to retreive, eg, v1.54.0"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
