name: Get AWS CDK Dependencies
description: Retrieves the Node.js packages from an AWS CDK release by tag
branding:
  icon: package
  color: purple
inputs:
  token:
    description: "Your GitHub token"
    required: true
  release:
    description: "The AWS CDK release to parse, eg, v1.61.0"
    required: true
  debug:
    required: false
    description: "Set to 'true' to get logging"
    default: "false"
runs:
  using: "docker"
  image: "Dockerfile"
